// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: presslabs/dashboard/organizations/v1/organization.proto

package v1 // import "github.com/presslabs/dashboard/pkg/api/organizations/v1"

import regexp "regexp"
import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/mwitkow/go-proto-validators"
import _ "google.golang.org/genproto/protobuf/field_mask"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_Organization_Name = regexp.MustCompile(`^orgs/[a-z0-9]([-a-z0-9]*[a-z0-9])?$`)

func (this *Organization) Validate() error {
	if !_regex_Organization_Name.MatchString(this.Name) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must be a string conforming to regex "^orgs/[a-z0-9]([-a-z0-9]*[a-z0-9])?$"`, this.Name))
	}
	if !(len(this.Name) > 8) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must length be greater than '8'`, this.Name))
	}
	if !(len(this.Name) < 53) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must length be less than '53'`, this.Name))
	}
	return nil
}

var _regex_GetOrganizationRequest_Name = regexp.MustCompile(`^orgs/[a-z0-9]([-a-z0-9]*[a-z0-9])?$`)

func (this *GetOrganizationRequest) Validate() error {
	if !_regex_GetOrganizationRequest_Name.MatchString(this.Name) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must be a string conforming to regex "^orgs/[a-z0-9]([-a-z0-9]*[a-z0-9])?$"`, this.Name))
	}
	if !(len(this.Name) > 8) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must length be greater than '8'`, this.Name))
	}
	if !(len(this.Name) < 53) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must length be less than '53'`, this.Name))
	}
	return nil
}
func (this *ListOrganizationsRequest) Validate() error {
	return nil
}
func (this *ListOrganizationsResponse) Validate() error {
	for _, item := range this.Organizations {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Organizations", err)
			}
		}
	}
	return nil
}

var _regex_CreateOrganizationRequest_OrganizationId = regexp.MustCompile(`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`)

func (this *CreateOrganizationRequest) Validate() error {
	if !_regex_CreateOrganizationRequest_OrganizationId.MatchString(this.OrganizationId) {
		return github_com_mwitkow_go_proto_validators.FieldError("OrganizationId", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"`, this.OrganizationId))
	}
	if !(len(this.OrganizationId) > 3) {
		return github_com_mwitkow_go_proto_validators.FieldError("OrganizationId", fmt.Errorf(`value '%v' must length be greater than '3'`, this.OrganizationId))
	}
	if !(len(this.OrganizationId) < 48) {
		return github_com_mwitkow_go_proto_validators.FieldError("OrganizationId", fmt.Errorf(`value '%v' must length be less than '48'`, this.OrganizationId))
	}
	if this.Organization != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Organization); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Organization", err)
		}
	}
	return nil
}
func (this *UpdateOrganizationRequest) Validate() error {
	if nil == this.Organization {
		return github_com_mwitkow_go_proto_validators.FieldError("Organization", fmt.Errorf("message must exist"))
	}
	if this.Organization != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Organization); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Organization", err)
		}
	}
	if this.UpdateMask != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdateMask); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdateMask", err)
		}
	}
	return nil
}

var _regex_DeleteOrganizationRequest_Name = regexp.MustCompile(`^orgs/[a-z0-9]([-a-z0-9]*[a-z0-9])?$`)

func (this *DeleteOrganizationRequest) Validate() error {
	if !_regex_DeleteOrganizationRequest_Name.MatchString(this.Name) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must be a string conforming to regex "^orgs/[a-z0-9]([-a-z0-9]*[a-z0-9])?$"`, this.Name))
	}
	if !(len(this.Name) > 8) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must length be greater than '8'`, this.Name))
	}
	if !(len(this.Name) < 53) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must length be less than '53'`, this.Name))
	}
	return nil
}
