// Code generated by protoc-gen-go. DO NOT EDIT.
// source: presslabs/dashboard/core/v1/project.proto

package v1 // import "github.com/presslabs/dashboard/pkg/api/core/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Project struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_46697faf9b3646d2, []int{0}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_46697faf9b3646d2, []int{1}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Project)(nil), "presslabs.dashboard.v1.Project")
	proto.RegisterType((*ListRequest)(nil), "presslabs.dashboard.v1.ListRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectsClient is the client API for Projects service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectsClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (Projects_ListClient, error)
}

type projectsClient struct {
	cc *grpc.ClientConn
}

func NewProjectsClient(cc *grpc.ClientConn) ProjectsClient {
	return &projectsClient{cc}
}

func (c *projectsClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (Projects_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Projects_serviceDesc.Streams[0], "/presslabs.dashboard.v1.Projects/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &projectsListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Projects_ListClient interface {
	Recv() (*Project, error)
	grpc.ClientStream
}

type projectsListClient struct {
	grpc.ClientStream
}

func (x *projectsListClient) Recv() (*Project, error) {
	m := new(Project)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProjectsServer is the server API for Projects service.
type ProjectsServer interface {
	List(*ListRequest, Projects_ListServer) error
}

func RegisterProjectsServer(s *grpc.Server, srv ProjectsServer) {
	s.RegisterService(&_Projects_serviceDesc, srv)
}

func _Projects_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProjectsServer).List(m, &projectsListServer{stream})
}

type Projects_ListServer interface {
	Send(*Project) error
	grpc.ServerStream
}

type projectsListServer struct {
	grpc.ServerStream
}

func (x *projectsListServer) Send(m *Project) error {
	return x.ServerStream.SendMsg(m)
}

var _Projects_serviceDesc = grpc.ServiceDesc{
	ServiceName: "presslabs.dashboard.v1.Projects",
	HandlerType: (*ProjectsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Projects_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "presslabs/dashboard/core/v1/project.proto",
}

func init() {
	proto.RegisterFile("presslabs/dashboard/core/v1/project.proto", fileDescriptor_project_46697faf9b3646d2)
}

var fileDescriptor_project_46697faf9b3646d2 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2c, 0x28, 0x4a, 0x2d,
	0x2e, 0xce, 0x49, 0x4c, 0x2a, 0xd6, 0x4f, 0x49, 0x2c, 0xce, 0x48, 0xca, 0x4f, 0x2c, 0x4a, 0xd1,
	0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x2f, 0x33, 0xd4, 0x2f, 0x28, 0xca, 0xcf, 0x4a, 0x4d, 0x2e, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x83, 0x2b, 0xd5, 0x83, 0x2b, 0xd5, 0x2b, 0x33, 0x54,
	0xd2, 0xe5, 0x62, 0x0f, 0x80, 0x28, 0x14, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x02, 0x8b, 0x80, 0xd9, 0x4a, 0xbc, 0x5c, 0xdc, 0x3e, 0x99, 0xc5, 0x25, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x46, 0x31, 0x5c, 0x1c, 0x50, 0xdd, 0xc5, 0x42, 0x01, 0x5c, 0x2c, 0x20, 0x29,
	0x21, 0x65, 0x3d, 0xec, 0x56, 0xe9, 0x21, 0x69, 0x94, 0x92, 0xc7, 0xa5, 0x08, 0x6a, 0x9c, 0x12,
	0x83, 0x01, 0xa3, 0x93, 0x41, 0x94, 0x5e, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e,
	0xae, 0x3e, 0x36, 0xbf, 0x16, 0x64, 0xa7, 0xeb, 0x27, 0x16, 0x64, 0xc2, 0xfc, 0x9c, 0xc4, 0x06,
	0xf6, 0xac, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x8a, 0xa2, 0x62, 0x19, 0x01, 0x00, 0x00,
}
