// Code generated by protoc-gen-go. DO NOT EDIT.
// source: projects/v1/project.proto

package project

import (
	"context"
	dashboardv1alpha1 "github.com/presslabs/dashboard/pkg/apis/dashboard/v1alpha1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type projectsServer struct {
	client client.Client
}

func (s *projectsServer) List(r *ListRequest, stream Projects_ListServer) error {
	projects := &dashboardv1alpha1.ProjectList{}

	err := s.client.List(context.TODO(), &client.ListOptions{}, projects)
	if err != nil {
		return err
	}

	for _, project := range projects.Items {
		stream.Send(NewFromK8s(&project))
	}

	return nil
}

func NewProjectServer(client client.Client) ProjectsServer {
	return &projectsServer{
		client: client,
	}
}

func NewFromK8s(p *dashboardv1alpha1.Project) *Project {
	return &Project{Id: p.Name, Name: p.Name}
}
