workspace:
  base: /go
  path: src/github.com/presslabs/dashboard

clone:
  git:
    image: plugins/git
    depth: 100
    tags: true

pipeline:
  dependencies:
    image: golang:1.11
    commands:
      - make dependencies

  lint:
    group: lint
    image: golang:1.11
    commands:
      - make lint

  lint-chart:
    group: lint
    image: quay.io/presslabs/kluster-toolbox
    pull: true
    commands:
      - helm lint chart/dashboard
      - helm dep build chart/dashboard

  test:
    image: golang:1.11
    commands:
      - make test

  build-chart:
    group: build-dep
    image: quay.io/presslabs/kluster-toolbox
    commands:
      - make chart

  publish:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/dashboard
    tags: [ "latest" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      branch: master
      event: push

  publish:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/dashboard
    tags: [ "${DRONE_TAG}" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: tag

  publish-chart:
    group: publish
    image: quay.io/presslabs/kluster-toolbox
    environment:
      - GH_USER=presslabs-bot
    commands:
      - cd chart
      - helm package dashboard
      - CHART="$(basename *.tgz)" ; MESSAGE="Publish $(basename $CHART .tgz)"
      - /usr/local/bin/gh put --skip-existing -m "$MESSAGE" "$CHART" "presslabs/charts/docs/"
    secrets:
      - GH_PASSWORD
    when:
      event: tag
