workspace:
  base: /go
  path: src/github.com/presslabs/dashboard

pipeline:
  lint:
    image: golang:1.10
    commands:
      - make dependencies
      - make lint

  test:
    image: golang:1.10
    commands:
      - make dependencies
      - make test

#  publish:
#    image: plugins/gcr
#    mirror: https://mirror.gcr.io
#    secrets:
#      - GOOGLE_CREDENTIALS
#    repo: pl-infra/presslabs-dashboard
#    tags: [ "latest" ]
#    when:
#      branch: master
#      event: push
