linters-settings:
  dupl:
    threshold: 400
  gocyclo:
    min-complexity: 10
  govet:
    check-shadowing: true
  lll:
    line-length: 170
    tab-width: 4

run:
  # TODO: re-enable tests linting and make them pass
  tests: false

linters:
  presets:
    - bugs
    - unused
    - format
    - style
    - complexity
    - performance

  # TODO: we should re-enable them and make lint pass
  disable:
    - goimports
    - maligned

issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    # gosec G104, about unhandled errors. We do that with errcheck already
    - "G104: Errors unhandled"
