required = [
    "github.com/gogo/protobuf/proto",
    "github.com/gogo/protobuf/jsonpb",
    "github.com/gogo/protobuf/protoc-gen-gogo",
    "github.com/gogo/protobuf/gogoproto",
    "github.com/ckaznocha/protoc-gen-lint",
    "google.golang.org/grpc",
    ]

[prune]
  go-tests = true

[[constraint]]
name="github.com/gogo/protobuf"
version="v1.2.0"

[[constraint]]
name="github.com/ckaznocha/protoc-gen-lint"
version="v0.2.1"

[[constraint]]
name="google.golang.org/grpc"
version="1.18.0"

