required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
]

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "github.com/coreos/prometheus-operator"
  branch = "master"

# gengo needs to be manually pinned to the version listed in code-generators
# Gopkg.toml, because the k8s project does not produce Gopkg.toml files & dep
# does not parse the Godeps.json file to determine revisions to use.
[[override]]
  name = "k8s.io/gengo"
  revision = "01a732e01d00cb9a81bb0ca050d3e6d2b947927b"

[[override]]
  name = "github.com/appscode/kutil"
  branch = "release-7.0"

# Fixes: cannot use spt.Token (type func() adal.Token) as type adal.Token in field value
[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v9.10.0"
