apiVersion: skaffold/v1beta7
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: quay.io/presslabs/dashboard
    docker:
      dockerfile: Dockerfile.skaffold
deploy:
  helm:
    releases:
    - name: dashboard
      chartPath: chart/dashboard
      values:
        image: quay.io/presslabs/dashboard
      setValues:
        apiserver.oidc.client_id: "TgYj4aR1ttmiZ0YexSwtHVKYSAOza2Vn"
        apiserver.oidc.client_secret: "Nmro5jF1Yx78RdHB5hHiYc-TvdNF96Dd1VR0Uo_3yM26AlLzIQ2TsU0oLWafnyvO"
        apiserver.oidc.issuer: "https://presslabs.auth0.com/"
