/*
Copyright 2018 Pressinfra SRL

This file is subject to the terms and conditions defined in file LICENSE,
which is part of this source code package.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/presslabs/dashboard/pkg/client/clientset/versioned/typed/projects/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDashboardV1alpha1 struct {
	*testing.Fake
}

func (c *FakeDashboardV1alpha1) Projects(namespace string) v1alpha1.ProjectInterface {
	return &FakeProjects{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDashboardV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
