/*
Copyright 2018 Pressinfra SRL

This file is subject to the terms and conditions defined in file LICENSE,
which is part of this source code package.
*/

// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated fake clientset.
package fake
