/*
Copyright 2018 Pressinfra SRL

This file is subject to the terms and conditions defined in file LICENSE,
which is part of this source code package.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ProjectListerExpansion allows custom methods to be added to
// ProjectLister.
type ProjectListerExpansion interface{}
